// <auto-generated />
using System;
using EKvarovi.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EKvarovi.Api.Migrations
{
    [DbContext(typeof(EKvaroviDbContext))]
    [Migration("20260828092526_AddSystemAppUserSeed")]
    partial class AddSystemAppUserSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("EKvarovi.Shared.Models.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AppRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Technician"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Reporter"
                        });
                });

            modelBuilder.Entity("EKvarovi.Shared.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Sistem",
                            Email = "sistem@ekvarovi.local",
                            IsActive = false,
                            PasswordHash = "SISTEM-RACUN-BEZ-PRIJAVE"
                        });
                });

            modelBuilder.Entity("EKvarovi.Shared.Models.AppUserRole", b =>
                {
                    b.Property<int>("AppUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppRoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AppUserId", "AppRoleId");

                    b.HasIndex("AppRoleId");

                    b.ToTable("AppUserRoles");
                });

            modelBuilder.Entity("EKvarovi.Shared.Models.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttachmentPurposeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FaultReportId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InterventionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UploadedByAppUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentPurposeId");

                    b.HasIndex("FaultReportId");

                    b.HasIndex("InterventionId");

                    b.HasIndex("UploadedByAppUserId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("EKvarovi.Shared.Models.AttachmentPurpose", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AttachmentPurposes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "FotografijaPrije"
                        },
                        new
                        {
                            Id = 2,
                            Name = "FotografijaPoslije"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dokument"
                        });
                });

            modelBuilder.Entity("EKvarovi.Shared.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReporter")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTechnician")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EKvarovi.Shared.Models.FaultPriority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("FaultPriorities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nizak",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Srednji",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Visok",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Kritičan",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("EKvarovi.Shared.Models.FaultReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FaultPriorityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FaultStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FaultTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReporterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FaultPriorityId");

                    b.HasIndex("FaultStatusId");

                    b.HasIndex("FaultTypeId");

                    b.HasIndex("LocationId");

                    b.HasIndex("ReporterId");

                    b.ToTable("FaultReports");
                });

            modelBuilder.Entity("EKvarovi.Shared.Models.FaultStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("FaultStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Zaprimljeno",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pregledano",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dodijeljeno",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "U radu",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Name = "Riješeno",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            Name = "Zatvoreno",
                            SortOrder = 6
                        });
                });

            modelBuilder.Entity("EKvarovi.Shared.Models.FaultType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("FaultTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Elektrika"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Voda"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Grijanje"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Mreža"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Građevinski radovi"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ostalo"
                        });
                });

            modelBuilder.Entity("EKvarovi.Shared.Models.Intervention", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("InterventionStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkAssignmentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InterventionStatusId");

                    b.HasIndex("WorkAssignmentId");

                    b.ToTable("Interventions");
                });

            modelBuilder.Entity("EKvarovi.Shared.Models.InterventionMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InterventionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("InterventionId");

                    b.HasIndex("MaterialId");

                    b.ToTable("InterventionMaterials");
                });

            modelBuilder.Entity("EKvarovi.Shared.Models.InterventionStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("InterventionStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Planirana"
                        },
                        new
                        {
                            Id = 2,
                            Name = "U tijeku"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Završena"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Neuspješna"
                        });
                });

            modelBuilder.Entity("EKvarovi.Shared.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocationTypeId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("EKvarovi.Shared.Models.LocationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LocationTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Upravna zgrada"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Škola"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Zdravstvena ustanova"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Skladište"
                        });
                });

            modelBuilder.Entity("EKvarovi.Shared.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaterialUnitId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MaterialUnitId");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("EKvarovi.Shared.Models.MaterialUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MaterialUnits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "kom",
                            Name = "Komad"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "m",
                            Name = "Metar"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "l",
                            Name = "Litra"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "kg",
                            Name = "Kilogram"
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "pak",
                            Name = "Paket"
                        });
                });

            modelBuilder.Entity("EKvarovi.Shared.Models.WorkAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("AssignedByAppUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FaultReportId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReassignmentNote")
                        .HasColumnType("TEXT");

                    b.Property<int>("TechnicianId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UnassignedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedByAppUserId");

                    b.HasIndex("FaultReportId")
                        .IsUnique()
                        .HasDatabaseName("IX_WorkAssignments_FaultReportId_ActiveOnly")
                        .HasFilter("\"IsActive\" = 1");

                    b.HasIndex("TechnicianId");

                    b.ToTable("WorkAssignments");
                });

            modelBuilder.Entity("EKvarovi.Shared.Models.AppUser", b =>
                {
                    b.HasOne("EKvarovi.Shared.Models.Employee", "Employee")
                        .WithOne("AppUser")
                        .HasForeignKey("EKvarovi.Shared.Models.AppUser", "EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EKvarovi.Shared.Models.AppUserRole", b =>
                {
                    b.HasOne("EKvarovi.Shared.Models.AppRole", "AppRole")
                        .WithMany("UserRoles")
                        .HasForeignKey("AppRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EKvarovi.Shared.Models.AppUser", "AppUser")
                        .WithMany("UserRoles")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppRole");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("EKvarovi.Shared.Models.Attachment", b =>
                {
                    b.HasOne("EKvarovi.Shared.Models.AttachmentPurpose", "AttachmentPurpose")
                        .WithMany("Attachments")
                        .HasForeignKey("AttachmentPurposeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EKvarovi.Shared.Models.FaultReport", "FaultReport")
                        .WithMany("Attachments")
                        .HasForeignKey("FaultReportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EKvarovi.Shared.Models.Intervention", "Intervention")
                        .WithMany("Attachments")
                        .HasForeignKey("InterventionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EKvarovi.Shared.Models.AppUser", "UploadedByAppUser")
                        .WithMany("UploadedAttachments")
                        .HasForeignKey("UploadedByAppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AttachmentPurpose");

                    b.Navigation("FaultReport");

                    b.Navigation("Intervention");

                    b.Navigation("UploadedByAppUser");
                });

            modelBuilder.Entity("EKvarovi.Shared.Models.Employee", b =>
                {
                    b.HasOne("EKvarovi.Shared.Models.Location", "Location")
                        .WithMany("Employees")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("EKvarovi.Shared.Models.FaultReport", b =>
                {
                    b.HasOne("EKvarovi.Shared.Models.FaultPriority", "FaultPriority")
                        .WithMany("FaultReports")
                        .HasForeignKey("FaultPriorityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EKvarovi.Shared.Models.FaultStatus", "FaultStatus")
                        .WithMany("FaultReports")
                        .HasForeignKey("FaultStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EKvarovi.Shared.Models.FaultType", "FaultType")
                        .WithMany("FaultReports")
                        .HasForeignKey("FaultTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EKvarovi.Shared.Models.Location", "Location")
                        .WithMany("FaultReports")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EKvarovi.Shared.Models.Employee", "Reporter")
                        .WithMany("ReportedFaultReports")
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FaultPriority");

                    b.Navigation("FaultStatus");

                    b.Navigation("FaultType");

                    b.Navigation("Location");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("EKvarovi.Shared.Models.Intervention", b =>
                {
                    b.HasOne("EKvarovi.Shared.Models.InterventionStatus", "InterventionStatus")
                        .WithMany("Interventions")
                        .HasForeignKey("InterventionStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EKvarovi.Shared.Models.WorkAssignment", "WorkAssignment")
                        .WithMany("Interventions")
                        .HasForeignKey("WorkAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InterventionStatus");

                    b.Navigation("WorkAssignment");
                });

            modelBuilder.Entity("EKvarovi.Shared.Models.InterventionMaterial", b =>
                {
                    b.HasOne("EKvarovi.Shared.Models.Intervention", "Intervention")
                        .WithMany("InterventionMaterials")
                        .HasForeignKey("InterventionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EKvarovi.Shared.Models.Material", "Material")
                        .WithMany("InterventionMaterials")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Intervention");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("EKvarovi.Shared.Models.Location", b =>
                {
                    b.HasOne("EKvarovi.Shared.Models.LocationType", "LocationType")
                        .WithMany("Locations")
                        .HasForeignKey("LocationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LocationType");
                });

            modelBuilder.Entity("EKvarovi.Shared.Models.Material", b =>
                {
                    b.HasOne("EKvarovi.Shared.Models.MaterialUnit", "MaterialUnit")
                        .WithMany("Materials")
                        .HasForeignKey("MaterialUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MaterialUnit");
                });

            modelBuilder.Entity("EKvarovi.Shared.Models.WorkAssignment", b =>
                {
                    b.HasOne("EKvarovi.Shared.Models.AppUser", "AssignedByAppUser")
                        .WithMany("AssignedWorkAssignments")
                        .HasForeignKey("AssignedByAppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EKvarovi.Shared.Models.FaultReport", "FaultReport")
                        .WithMany("WorkAssignments")
                        .HasForeignKey("FaultReportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EKvarovi.Shared.Models.Employee", "Technician")
                        .WithMany("WorkAssignments")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedByAppUser");

                    b.Navigation("FaultReport");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("EKvarovi.Shared.Models.AppRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("EKvarovi.Shared.Models.AppUser", b =>
                {
                    b.Navigation("AssignedWorkAssignments");

                    b.Navigation("UploadedAttachments");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("EKvarovi.Shared.Models.AttachmentPurpose", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("EKvarovi.Shared.Models.Employee", b =>
                {
                    b.Navigation("AppUser");

                    b.Navigation("ReportedFaultReports");

                    b.Navigation("WorkAssignments");
                });

            modelBuilder.Entity("EKvarovi.Shared.Models.FaultPriority", b =>
                {
                    b.Navigation("FaultReports");
                });

            modelBuilder.Entity("EKvarovi.Shared.Models.FaultReport", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("WorkAssignments");
                });

            modelBuilder.Entity("EKvarovi.Shared.Models.FaultStatus", b =>
                {
                    b.Navigation("FaultReports");
                });

            modelBuilder.Entity("EKvarovi.Shared.Models.FaultType", b =>
                {
                    b.Navigation("FaultReports");
                });

            modelBuilder.Entity("EKvarovi.Shared.Models.Intervention", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("InterventionMaterials");
                });

            modelBuilder.Entity("EKvarovi.Shared.Models.InterventionStatus", b =>
                {
                    b.Navigation("Interventions");
                });

            modelBuilder.Entity("EKvarovi.Shared.Models.Location", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("FaultReports");
                });

            modelBuilder.Entity("EKvarovi.Shared.Models.LocationType", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("EKvarovi.Shared.Models.Material", b =>
                {
                    b.Navigation("InterventionMaterials");
                });

            modelBuilder.Entity("EKvarovi.Shared.Models.MaterialUnit", b =>
                {
                    b.Navigation("Materials");
                });

            modelBuilder.Entity("EKvarovi.Shared.Models.WorkAssignment", b =>
                {
                    b.Navigation("Interventions");
                });
#pragma warning restore 612, 618
        }
    }
}
